### ISSUE TITLE
Old version of Stripe

### ISSUE THREAD

**Issue by xeonarno** [vicary/node-red-contrib-stripe#2]
The current version is Stripe v5.5 but the actual nodejs version is 7.1

**Comment by vicary** [comment]
@xeonarno Give the branch [`Upgrade-stripe-to-7.4.0`](https://github.com/vicary/node-red-contrib-stripe/tree/Upgrade-stripe-to-7.4.0) a try if you'd like so, I'll merge it in a week or two.

**Comment by vicary** [comment]
Merged to master, closing this. Feel free to reopen on follow-ups.
