### ISSUE TITLE
Is this the right node for me? 

### ISSUE THREAD

**Issue by Nornode** [vicary/node-red-contrib-stripe#4]
I'm sorry, This was the only way I understood how to connect with you.  
This might not be an issue other than possibly better documentation?

I want to pull and interact with information from a vendor that uses Stripe.
I want to pull that information which I can see in chrome Dev window being served inside a JSON. However, I have troubles adjusting the CURL to continuously pull (not even thinking about sending commands yet) as the Stripe key changes every 24h.

Can your nodes help me in a Node-Red flow?

I'm thinking: 
Service URL/API call with my credentials -> Your magic Nodes adds and updates Stripe API keys -> Feed Response JSON to MQTT/anything else.

b.t.w. When will you push updates for your nodes to be able to pull them inside Node-Red?

**Comment by vicary** [comment]
Not really sure what you wanna do with your vendor, but does a rolling key mean they don't want what you're trying to do?

Stripe config nodes provides better security for credentials (secrets), supporting dynamic credentials means a sacrifice in security and also implies a managed LRU cache of credentials-to-`Stripe` mapping.

I don't see node-red did anything like this so far, not sure if they encourage this pattern TBH.

I need a stronger use case, or more context maybe, to do this myself. But if you understand what I mean above, you can make a PR.

P.S. `0.1.3` is deployed.

**Comment by Nornode** [comment]
Hi, sorry for a very long turn around time on this. Life happened...

Yeah, so a service I pay for is offering a web service/portal (https://my.webastoconnect.com/) where I can read my information when logged in. Now that information is delivered as a JSON so it would be perfect to take in on Node-Red and forward into other services.

However, I'm unfortunately unable to automatically authenticate, get credential tokens, and have the correct JSON response I get when I use the developer console in chrome.

This is the cURL command I get from Chrome dev console:
```
curl 'https://my.webastoconnect.com/webapi/get_service_data?poll=true&_=TIMESTAMP' \
    -H 'Connection: keep-alive' \
    -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'DNT: 1' \
    -H 'X-Requested-With: XMLHttpRequest' \
    -H 'User-Agent: SOME-USER-AGENT' \
    -H 'Sec-Fetch-Site: same-origin' \
    -H 'Sec-Fetch-Mode: cors' \
    -H 'Referer: https://my.webastoconnect.com/index.html?lang=en' \
    -H 'Accept-Encoding: gzip, deflate, br' \
    -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,sv;q=0.7' \
    -H 'Cookie: __stripe_mid=XXXXXXXX-0a45-4037-9078-XXXXXXXXXXX; \
        i18next=en; \
        lang=en; \
        cookies_confirmed=true; \
        webclient_advanced_settings=false; \
        hssess=XXXXXXXXXXXXXX; \
        __stripe_sid=XXXXXXXX-dc5b-4df0-8f84-XXXXXXXXXXXXXX' \
    --compressed
```

So is it possible with your node to fetch and store a client cookie to use in this way, or which other nodes would you recommend?

**Comment by vicary** [comment]
No worries, I am still maintaining this repo.

Your fetch can be done with the original http node, this node can take the result and instantiate the Stripe object with that.

Do you think you can make a PR? I am working on some other projects so I may not have time for this quite soon.

Here's what it should change,
1. Move the calls of `.getInstance()` into the input handler.
2. Change `.getInstance()` into `.getInstance({ secret: "..." })` and fallback to secret if it's not present.
3. Reuse existing Stripe instances if the same secret is specified, either plain object or `lru-cache` works.
4. Maybe hashing the secret to prevent the secret from appearing in heap dump?
