### ISSUE TITLE
Arguments in payload ignored

### ISSUE THREAD

**Issue by hackatore** [vicary/node-red-contrib-stripe#5]
I have spent several hours trying different combinations of arguments and they seem to be ignored.

Examples
msg.payload = ['customer',{limit:3}];
msg.payload = [{limit:3}];
msg.payload = [null,'limit:3'];
msg.payload = [null,{limit:3}];
msg.payload = 'cus_EJP04Nywe9KxUJ';
Etc. 

In the case of stripe.customer.list I get a result of 10 customers no matter what I do. 

What am I doing wrong?   I can't seem top limit the number of results by either the limit option or by specifying a customer id or subscription id.

**Comment by vicary** [comment]
It just normalises the payload into an array, https://github.com/vicary/node-red-contrib-stripe/blob/cacc1eaa60230b03e11b370069b19a17d5f0eb43/nodes/01-api.js#L48
And uses it to invoke the method after adding idempotency key, https://github.com/vicary/node-red-contrib-stripe/blob/cacc1eaa60230b03e11b370069b19a17d5f0eb43/nodes/01-api.js#L66

In theory it should work for `{ limit: 3 }`, I’ll do some tests in a few days to be sure.
