### ISSUE TITLE
Cannot install :(

### ISSUE THREAD

**Issue by Swiftnesses** [vicary/node-red-contrib-stripe#7]
Hello,

I am trying to install this but am getting the following error:

`Cannot find module '/data/node_modules/node-red-contrib-stripe/dist/stripe.js'"`

Any ideas?

I've already run the --save command at the Node Red root.

**Comment by Swiftnesses** [comment]
Good day,

Any ideas what I'm doing wrong?

**Comment by vicary** [comment]
Should be a misconfiguration when I port to TypeScript, I'll fix it this weekend.

In the mean time you can navigate to `node_modules/node-red-contrib-stripe` and run `npm run build` to temporarily fix that.

**Comment by vicary** [comment]
@Swiftnesses try installing 0.2.4, it should work fine now.

**Comment by Swiftnesses** [comment]
@vicary I'll check, thank you :)
